### ISSUE TITLE
data source for sumologic_collector

### ISSUE THREAD

**Issue by marionettist** [SumoLogic/sumologic-terraform-provider#11]
It would be nice if the provider had a data source for sumologic_collector.
It would be useful in cases where a terraform stack creates data sources but expects the collector to be already present (e.g. created by another terraform stack).

If no one is working or planning to work on this, I might be able to help if you would consider a pull request for this feature.

By the way, great job on the provider in general.

**Comment by frankreno** [comment]
@marionettist thanks for the feedback and issue.  I think this enhancement makes a lot of sense.  There is a way to potentially achieve this in some situations, where you have a collector perhaps created somewhere else.  There is a property on collectors and sources called `lookup_by_name` that defaults to `false`.  If set to true, and a collector with the same name exists, it will use that one.  If it does not exist, it will create a new one.

**Comment by frankreno** [comment]
Oh, and we would love a PR for any enhancement.  I am going to look at the current open issues over the next week or so to resolve and get a new release out so if you want to submit an enhancement, we would welcome it!

**Comment by marionettist** [comment]
Using the lookup_by_name attribute works pretty well, but of course it means that different terraform stack could potentially manage the same resource and could potentially do it in different ways. Therefore, if you don't mind, I'd like you to leave this issue open for now as I'm planning on creating pull request in the not-so-distant future.

**Comment by frankreno** [comment]
fixed in v0.2.0
