### ISSUE TITLE
collector not re-created after manual deletion

### ISSUE THREAD

**Issue by marionettist** [SumoLogic/sumologic-terraform-provider#19]
If, after doing a terraform apply that creates a collector, the collector is deleted manually, the collector is not created after another terraform apply.
Will create a PR

**Comment by marionettist** [comment]
I have change ready to fix this but will submit the PR after [pull request 18](https://github.com/SumoLogic/sumologic-terraform-provider/pull/18) has been merged

**Comment by frankreno** [comment]
fixed in v0.2.0
