### ISSUE TITLE
drop the lookup_by_name attribute

### ISSUE THREAD

**Issue by marionettist** [SumoLogic/sumologic-terraform-provider#29]
The `lookup_by_name` attribute provides a nice and easy way of creating a resource or retrieving the id of one that already exists. When I first started using this provider, it certainly got me round an issue I had.

However, I think that it might be time to pull the plug on that attribute before the provider gets more widely used...

The reason for this is that I think it's working in a way that is against the terraform philoshophy and here's an example.

Let's imagine that we have 2 terraform stacks creating data sources of the same type. They are in different stacks because the data sources are associated with resources created in different stacks (e.g. ELB logs in different accounts).

So in the first stack, we have:
```hcl
resource "sumologic_collector" "this" {
  name = "foo"
  description = "my desc"
  category = "my/cat"
  lookup_by_name = true
}

resource "sumologic_polling_source" "this" {
  name          = "ELB-logs-account-A"
  collector_id  = "${sumologic_collector.this.id}"
  # other attributes...
}
```

Then in the second stack, we have:
```hcl
resource "sumologic_collector" "this" {
  name = "foo"
  description = "another desc"
  category = "another/cat"
  lookup_by_name = true
}

resource "sumologic_polling_source" "this" {
  name          = "ELB-logs-account-B"
  collector_id  = "${sumologic_collector.this.id}"
  # other attributes...
}
```

Note the different values for description and category. Of course, in the real, this difference would not be intentional.
They might start as the same values, but a required change to the category somehow changes most stacks, but not all ( accidentally leaving some old values behind).

This all works reasonably well at first: an apply of the first stack is successful and a second apply is clean (with no differences).
When the 2nd stack is applied, that's succesful too and a second apply is again clean.

The issue raises its head when going back to the first stack and doing another apply (when no changes in that stack occurred): this time, because the descripion and categories have been changed by the second stack, there is difference.

You get the picture, if the first stack is applied, followed by the second stack, it will report that the apply has differences too. And so and so forth...

In my opinion, the correct way of handling this is by having 3 stacks:
* one that takes care of creating the collector and manages it
* one stack for each of the stacks described above, specifically to manage each data source

In the olden days, before terraform data sources were available, the sumo data source stacks would have had to read the collector's state remote state and get the collector id from it as an output.

But since terraform has been improved with (terraform) data sources, the code is simpler to write (imho) but also more loosely coupled. That's why I thought that a terraform data source for collectors would be a good idea.

Here's what the new code looks like:

collector stack
```hcl
resource "sumologic_collector" "this" {
  name = "foo"
  description = "my desc"
  category = "my/cat"
  lookup_by_name = true
}
```

1st data source stack
```hcl
data "sumologic_collector" "this" {
    name = "foo"
}

resource "sumologic_polling_source" "this" {
  name          = "ELB-logs-account-A"
  collector_id  = "${data.sumologic_collector.this.id}"
  # other attributes...
}
```

2nd data source stack
```hcl
data "sumologic_collector" "this" {
    name = "foo"
}

resource "sumologic_polling_source" "this" {
  name          = "ELB-logs-account-A"
  collector_id  = "${data.sumologic_collector.this.id}"
  # other attributes...
}
```

The inconsitency issue we had initially has now gone because every resource is managed in one stack and one stack only.

So, I know this is a breaking interface change, which I is why I described the issue in detail, but I still think we should go for it and drop the `lookup_by_name` attribute.

Thoughts? Shall we drop support for that attribute?

**Comment by horjulf** [comment]
With the addiction of data sources, it makes sense to move in this direction.
Initially we added both `lookup_by_name` and `destroy` flags to workaround deployments of the same stack in different environments/regions.

Managing the collectors in an independent stack/project is probably the best approach.

**Comment by seansain** [comment]
Deprecated in #136 - closing issue
