### ISSUE TITLE
drop the destroy attribute?

### ISSUE THREAD

**Issue by marionettist** [SumoLogic/sumologic-terraform-provider#30]
I think we might have no need for the `destroy` attribute.
As a reminder, it's an attribute that is true by default, but can be set to false to get terraform not to destroy the resource.

So if `destroy` is set to false and a `terraform destroy` is applied, the resource is removed from the terraform state but not deleted from the sumo account.

All resources support the terraform meta-attributes. One of them offers similar functionality to the `destroy` attribute.

The following block could be added to e.g. a sumologic_collector resource:
```hcl
resource "sumologic_collector" "this" {
    name = "foo"
    lifecycle {
        prevent_destroy = true
    }
}
```

This would prevent a `terraform destroy` from being successful. An error would occur.
If the user really wanted to destroy the resource, they would have to change the value of `prevent_destroy`.

If they wanted terraform to no longer manage the resource, they would have to remove it from the state file by running:
```bash
terraform state rm sumologic_collector.this
``` 

A potentially more useful attribute to have might be `force_destroy` with the following behaviour:
* if a resources (e.g. a collector) does not contain other resources (e.g. no data sources) the resource would be deleted normally when requested
* however, if a resource did contain sub-resources, the resource would only be deleted if `force_destroy` was set to `true`

This would be a similar behaviour to `aws_s3_bucket` and `aws_iam_user` for their similarly named attributes.

Since another breaking interface change is proposed (regarding [getting rid of the `lookup_by_name attribute`](https://github.com/SumoLogic/sumologic-terraform-provider/issues/29)), if that other change goes ahead, shall we take that opportunity to also get rid of the `destroy` attribute?

**Comment by horjulf** [comment]
Blocking a destroy on a collector with resources was the primary objective of the flag, changing the behavior to block by default makes sense since it can have a big impact (deleting a resource by mistake can be ok, however a collector with hundreds of sources 👎).

Agree with adding `force_destroy` as an alternative to force the collector to be destroyed with the sources.

**Comment by seansain** [comment]
Deprecated in #136 - closing issue
