### ISSUE TITLE
Add releases with assets

### ISSUE THREAD

**Issue by darend** [SumoLogic/sumologic-terraform-provider#5]
Can you generate a release with the assets similar to the original repository https://github.com/erikvanbrakel/terraform-provider-sumologic/releases/tag/v0.3.3

This makes it easier to use the provider without having to build it

**Comment by frankreno** [comment]
@darend definitely on my to do list...

**Comment by keir-rex** [comment]
We'd really like to see this as it leaves us a bit stuck in the meantime.

**Comment by frankreno** [comment]
Thanks to @kb18951452 this is now done.

**Comment by frankreno** [comment]
FYI, you may notice the releases contain multiple duplicate files.  The issue appears to be related to a regression in goreleaser, which we are using to package things up. More details here, we will work on addressing once this gets fixed. https://github.com/goreleaser/goreleaser/issues/836
