### ISSUE TITLE
Terraform 0.12 compatibility

### ISSUE THREAD

**Issue by hamstah** [SumoLogic/sumologic-terraform-provider#52]
Hi,

The provider is not compatible with terraform 0.12 
```
Error: failed to load provider "sumologic": Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

Are there any plans on making it compatible?

Thanks

**Comment by hamstah** [comment]
Fixed in #53

**Comment by e1ven** [comment]
Silly question, but does 1.0.0 contain the .12 changes?

When I run with the file from the release page (64 bit linux) shasum `da348a1e36bb0ed3dd8e99e29d040ed84ccaef41` I still seem to get the "Incompatible API version with plugin." message.

I get similar behavior on MacOS, when using the 1.0.0 zip file.

When I manually build from source, it seems to work as expected.

**Comment by hamstah** [comment]
The version built from master works for me in 0.12.3 and 0.12.4

Are you building yourself or use the releases?

**Comment by e1ven** [comment]
When I build it manually it seems to work, when I use the 1.0.0 release it doesn't seem to.

That's why I was asking if this fix had made it into 1.0.0 - The changelog suggests it did, but it isn't working in my tests, so I'm trying to find if I'm doing something wrong or it's not in a release yet.

**Comment by majormoses** [comment]
@e1ven can't speak to if the binary contains it but its tagged release has it: https://github.com/SumoLogic/sumologic-terraform-provider/tree/v1.0.0

**Comment by mikesphar** [comment]
Just for the record I was having the same problem and downloading the 1.0 tgz and building it myself fixed it.  The pre-built binary that is posted appears to be incorrect and not truly a 1.0 release.

**Comment by frankreno** [comment]
Odd, not sure what happened with the goreleaser process. Let me investigate this.

**Comment by hgontijo** [comment]
I also confirm that I had issues with released Linux and MacOS binaries. I cloned the repo, compiled and it worked fine -- https://github.com/hgontijo/sumologic-terraform-provider/releases/tag/v1.0.0.

**Comment by frankreno** [comment]
Can confirm it seems the goreleaser process did not pick up the 0.12 support for PR but not sure why.  WIll get this updated today

**Comment by frankreno** [comment]
Hrmm, can folks having issues with the releases make sure they do not have an older version of the plugin in `~/.terraform.d/plugins` and that `.terraform/plugins/*/lock.json` points to the right shasum in `checkums.txt` on the releases page?

**Comment by frankreno** [comment]
Ok I have recreated the release and tested and works on my end.  @hgontijo @mikesphar @e1ven let me know if you have issues, will close this out now.

**Comment by hgontijo** [comment]
Thanks @frankreno, it worked with Terraform 0.12.
