### ISSUE TITLE
Get exec format error when running release 0.3.0 on Mac OS

### ISSUE THREAD

**Issue by AmitMatsil** [SumoLogic/sumologic-terraform-provider#55]
Hello,
I've downloaded 0.3.0 release from here: https://github.com/SumoLogic/sumologic-terraform-provider/releases/download/v0.3.0/sumologic-terraform-provider_0.3.0_macOS_64-bit.zip 
but I'm getting: `fork/exec /Users/amit/.terraform_plugins/terraform-provider-sumologic: exec format error`
uname -a: `Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64`

Thank you for your help, 
Amit.

**Comment by bendrucker** [comment]
Please share some more info, namely:

* OS version
* Terraform version
* Command with complete output

That also doesn't seem like the right terraform plugin dir, that might be your problem.

https://www.terraform.io/docs/extend/how-terraform-works.html#discovery

**Comment by AmitMatsil** [comment]
I'm using wrapper for Terraform (therefore the different path of the plugins). 
System Version: macOS 10.13.6 (17G5019)
Kernel Version: Darwin 17.7.0
Terraform version: v0.11.11

`Initializing modules...
- module.kafka_cluster
  Getting source "../aiven-kafka"
- module.admin_user
  Getting source "../aiven-kafka-user"
- module.ksql_user
  Getting source "../aiven-kafka-user"
- module.ingestion_user
  Getting source "../aiven-kafka-user"
- module.integration_user
  Getting source "../aiven-kafka-user"
- module.totango_users_user
  Getting source "../aiven-kafka-user"

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 1.60"
* provider.null: version = "~> 2.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
[terragrunt] 2019/06/16 16:05:57 Detected 1 Hooks
[terragrunt] 2019/06/16 16:05:57 Running command: terraform plan -var-file=/Users/amit/totango-repos/terraform-live/test/us-east-1/global/kafka-cluster/dnacx-bus/../../../../env.tfvars -out /var/folders/v4/dm69gm3j18sc1_n7q5sqjtqh0000gn/T/tmp.MBBJQYjQ

Error: Error asking for user input: 1 error(s) occurred:

* module.kafka_cluster.provider.sumologic: fork/exec /Users/amit/.terraform_plugins/terraform-provider-sumologic: exec format error


[terragrunt] 2019/06/16 16:06:06 Hit multiple errors:
exit status 1
Failed to parse plan. Returning original input.
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...`

**Comment by bendrucker** [comment]
Can you try executing the plugin directly? It should print:

```
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

If not it's probably the wrong binary.

**Comment by AmitMatsil** [comment]
I'm sorry it was a bug in our wrapper script. Thank you for your help!
