### ISSUE TITLE
sumologic_scheduled_view example in the documentation, is not worked

### ISSUE THREAD

**Issue by sehunpak** [SumoLogic/sumologic-terraform-provider#80]
Hi,

I'm new to using this provider and I've been trying to get the sumologic__scheduled_view working flow logs using the scheduled view example in the documentation. I'm also quite new to Terraform so go easy on me if I'm doing something stupid.

```
resource "sumologic_scheduled_view" "failed_connections" {
  index_name = "failed_connections"
  query = <<QUERY
_view=connections connectionStats
| parse "connectionStats.CS *" as body
| json field=body "exitCode", "isHttp2"
| lookup org_name from shared/partners on partner_id=partnerid
| timeslice 10m
QUERY
  start_time = "2019-09-01T00:00:00Z"
  retention_period = 365
}

```

**the result**

```
sumologic_scheduled_view.failed_connections: Creating...

Error: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /api/scheduledViews. Reason:
<pre>    Not Found</pre></p>
</body>
</html>
```

Status Codes 404 is notfound, Requested resource could not be found.
is this api working well?

**Comment by mccartney** [comment]
Thanks for reporting. I think you are not doing anything wrong and I actually found a bug in the scheduled_view resource implementation. Fixed that in #81.

Try now and let us know if it doesn't work.
