### ISSUE TITLE
Import budget by id does not work

### ISSUE THREAD

**Issue by hamstah** [SumoLogic/sumologic-terraform-provider#90]
Hi,
I tried to import an ingest budget using the id returned in the the UI, my id looks like
`000000000000XYXX` where X are numbers and Y is a letter.

I checked the id with an update in the UI and it seems correct.
I don't get much output except 

```
Error: unable to find ingest budget '000000000000XYXX'
```
Thanks

**Comment by seansain** [comment]
Ingest Budgets are imported by name.
